// ============================================================
// Create Workshop Use Case
// Clean Architecture: Application Business Rules Layer
// ============================================================

import type { WorkshopRepository } from '@/domain/repositories'
import type { AuditPort, SessionPort } from '@/application/ports'
import type { CreateWorkshopRequest } from '@/application/dtos'
import { Workshop } from '@/domain/entities'
import { ValidationError } from '@/domain/errors'

export class CreateWorkshopUseCase {
  constructor(
    private workshopRepository: WorkshopRepository,
    private auditPort: AuditPort,
    private sessionPort: SessionPort,
  ) {}

  async execute(request: CreateWorkshopRequest, sessionRequest?: Request) {
    // 1. Authenticate
    const user = sessionRequest
      ? await this.sessionPort.getSessionUser(sessionRequest)
      : null
    if (!user) {
      throw new ValidationError('No autenticado')
    }

    // 2. Validate
    if (!request.name) {
      throw new ValidationError('El nombre del taller es requerido')
    }

    // 3. Generate slug if not provided
    const slug = request.slug || Workshop.generateSlug(request.name)

    // 4. Check slug uniqueness
    const existing = await this.workshopRepository.findBySlug(slug)
    if (existing) {
      throw new ValidationError('Ya existe un taller con ese slug')
    }

    // 5. Create workshop entity
    const workshop = Workshop.create({
      id: '', // Will be generated by Prisma
      name: request.name,
      slug,
      description: request.description,
      address: request.address,
      phone: request.phone,
      email: request.email,
      currency: request.currency,
      timezone: request.timezone,
    })

    // 6. Persist
    const savedWorkshop = await this.workshopRepository.create(workshop)

    // 7. Add creator as owner
    await this.workshopRepository.addMember(savedWorkshop.id, user.id, 'owner')

    // 8. Log audit
    await this.auditPort.log({
      userId: user.id,
      userName: user.name,
      action: 'CREATE',
      entity: 'workshop',
      entityId: savedWorkshop.id,
      details: `Taller creado: ${request.name}`,
    })

    // 9. Return with role
    return {
      ...savedWorkshop.toPlainObject(),
      userRole: 'owner' as const,
    }
  }
}
